# Calls inside a loop

## 基本情况
* Check: calls-loop
* Severity: Low
* Confidence: Medium

## 描述
Calls inside a loop might lead to a denial-of-service attack.

## 利用案例
```solidity
contract CallsInLoop{

    address[] destinations;

    constructor(address[] newDestinations) public{
        destinations = newDestinations;
    }

    function bad() external{
        for (uint i=0; i < destinations.length; i++){
            destinations[i].transfer(i);
        }
    }

}
```
If one of the destinations has a fallback function that reverts, bad will always revert.

## 推荐方式
Favor pull over push strategy for external calls.

